// Epigraphs for the Today tab and level-ups: [quote, author].
// The first block are the quotes the Classroom of the Elite episodes open with (seasons 1 to 3).
window.__acEpigraphs = [
  ["What is evil? Whatever springs from weakness.", "Friedrich Nietzsche"],
  ["It takes a great talent and skill to conceal one's talent and skill.", "François de La Rochefoucauld"],
  ["Man is an animal that makes bargains: no other animal does this. No dog exchanges bones with another.", "Adam Smith"],
  ["We should not be upset that others hide the truth from us when we hide it from ourselves.", "François de La Rochefoucauld"],
  ["Hell is other people.", "Jean-Paul Sartre"],
  ["There are two kinds of lies: one concerns an accomplished fact, the other concerns a future duty.", "Jean-Jacques Rousseau"],
  ["Nothing is as dangerous as an ignorant friend; a wise enemy is to be preferred.", "Jean de La Fontaine"],
  ["Abandon all hope, ye who enter here.", "Dante Alighieri"],
  ["Man is condemned to be free.", "Jean-Paul Sartre"],
  ["Every man has in himself the most dangerous traitor of all.", "Søren Kierkegaard"],
  ["What people commonly call fate is mostly their own stupidity.", "Arthur Schopenhauer"],
  ["Genius lives only one story above madness.", "Arthur Schopenhauer"],
  ["Remember to keep a clear head in difficult times.", "Horace"],
  ["There are two main human sins from which all the others derive: impatience and indolence.", "Franz Kafka"],
  ["The greatest souls are capable of the greatest vices as well as of the greatest virtues.", "René Descartes"],
  ["Every failure is a step to success.", "William Whewell"],
  ["Adversity is the first path to truth.", "Lord Byron"],
  ["To doubt everything or to believe everything are two equally convenient solutions; both dispense with the necessity of reflection.", "Henri Poincaré"],
  ["If you make a mistake and do not correct it, this is called a mistake.", "Confucius"],
  ["People, often deceived by an illusive good, desire their own ruin.", "Niccolò Machiavelli"],
  ["A man who cannot command himself will always be a slave.", "Johann Wolfgang von Goethe"],
  ["Force without wisdom falls of its own weight.", "Horace"],
  ["The worst enemy you can meet will always be yourself.", "Friedrich Nietzsche"],
  ["The strongest principle of growth lies in the human choice.", "George Eliot"],
  ["Man is wolf to man.", "Plautus"],
  ["We never forget what we endeavour to forget.", "Friedrich Nietzsche"],
  ["To work you have the right, but not to the fruits thereof.", "Bhagavad Gita"],
  ["Fortune favours the bold.", "Virgil"],
  ["It is better to receive an injury than to inflict one.", "Cicero"],
  ["People will do anything, no matter how absurd, in order to avoid facing their own souls.", "Carl Jung"],
  ["Those who cannot remember the past are condemned to repeat it.", "George Santayana"],
  ["Extreme justice is extreme injustice.", "Cicero"],
  ["The first cause of absurd conclusions I ascribe to the want of method.", "Thomas Hobbes"],
  ["There is only one rule in love: bring happiness to those you love.", "Stendhal"],
  ["Change your desires rather than the order of the world.", "René Descartes"],
  ["Love is the best teacher.", "Pliny the Younger"],
  ["Whatever is done out of love always takes place beyond good and evil.", "Friedrich Nietzsche"],
  ["Man is born free, and everywhere he is in chains.", "Jean-Jacques Rousseau"],
  ["Everyone sees what you appear to be; few know what you really are.", "Niccolò Machiavelli"],
  ["Appear weak when you are strong, and strong when you are weak.", "Sun Tzu"],
  ["He who has a why to live can bear almost any how.", "Friedrich Nietzsche"],
  ["Knowing others is intelligence; knowing yourself is true wisdom.", "Lao Tzu"],
  ["No one is free who is not master of himself.", "Epictetus"],
  ["The first and best victory is to conquer yourself.", "Plato"],
  ["It is not that we have a short time to live, but that we waste much of it.", "Seneca"],
  ["The two most powerful warriors are patience and time.", "Leo Tolstoy"],
  ["The unexamined life is not worth living.", "Socrates"],
  ["All things are difficult before they are easy.", "Thomas Fuller"],
  ["He who would learn to fly one day must first learn to stand and walk.", "Friedrich Nietzsche"],
  ["The wise man does at once what the fool does finally.", "Niccolò Machiavelli"],
  ["Victorious warriors win first and then go to war.", "Sun Tzu"],
  ["Silence is a source of great strength.", "Lao Tzu"],
  ["Waste no more time arguing what a good man should be. Be one.", "Marcus Aurelius"],
  ["We suffer more often in imagination than in reality.", "Seneca"]
];

// Key ideas, summarised in plain words.
// Each idea: [title, one-line summary, [paragraphs...], "Try this" action].
// Add a book by appending an object with the same shape.
window.__acBooks = [
  {
    id: "subtle", title: "The Subtle Art of Not Giving a F*ck", short: "Subtle Art", author: "Mark Manson", tint: "amber",
    gist: "You can't care about everything, so choose carefully what you care about. A good life isn't free of problems. It's full of problems worth having.",
    ideas: [
      ["Care about fewer things",
        "Your attention is limited. Spend it on what actually matters and let the rest go.",
        ["The title is not an instruction to be indifferent. It is about being selective. Every day you are pulled towards a thousand small concerns: what someone said, how you look, whether a stranger online agrees with you. Each one takes a slice of your energy, and together they leave very little for the things you would actually be proud of.",
         "Not caring, in this sense, means being comfortable being different from other people when something truly matters to you. You pick a handful of things that deserve your full effort and deliberately shrug at everything else. That isn't laziness. It's triage.",
         "The people who seem calm and unbothered usually aren't numb. They have simply decided in advance what is worth reacting to."],
        "Write down the five things you most want to give your energy to this year. Next time something annoys you, ask whether it's on that list. If it isn't, let it go."],
      ["Choose your struggle",
        "Everything you want comes with pain. Pick the pain you're happy to keep paying for.",
        ["Everyone wants the outcome: the fit body, the successful business, the great relationship. Far fewer people want the process: early mornings, rejection, boring repetition, awkward conversations. The question that tells you more is not what you want to enjoy, but what pain you are willing to sustain.",
         "If you love the idea of being a musician but hate practising, you don't really want to be a musician. You want the image of one. People who succeed at something have usually fallen in love with the struggle itself, or at least accepted it as the price.",
         "This reframes discipline. You aren't failing because you lack willpower. You may have picked a goal whose daily cost you don't actually want to pay."],
        "Take one goal you keep failing at. List what the daily grind of it really looks like. Decide honestly whether you want that grind, or whether you should pick a different goal."],
      ["Chasing good feelings backfires",
        "Constantly wanting to feel better just reminds you that you don't.",
        ["Manson calls this the feedback loop from hell. You feel anxious, then get anxious about being anxious. You feel sad, then feel guilty for being sad. Modern culture keeps telling us we should feel great all the time, so any negative feeling starts to seem like a personal failure.",
         "Wanting a positive experience is itself a negative experience, because it highlights what you lack. Accepting a negative feeling, on the other hand, is oddly positive: once you stop fighting it, it tends to shrink and pass.",
         "Pain and discomfort are useful information. They tell you something needs attention. Numbing them or running from them means missing the message."],
        "The next time you feel low, don't try to fix it straight away. Name the feeling, sit with it for two minutes, and notice that it doesn't destroy you."],
      ["Responsibility is not fault",
        "Plenty of what happens to you isn't your fault. How you respond is still your job.",
        ["Fault is about the past: who caused this? Responsibility is about the present: what do I do now? A person can be dealt a terrible hand through no fault of their own, and it is still entirely up to them how they play it.",
         "This sounds harsh, but it's actually freeing. As long as you wait for someone else to fix what happened to you, you have no power. The moment you accept responsibility for your response, you get your power back.",
         "You are always choosing, even when you think you aren't. Doing nothing is also a choice. The only question is whether you choose deliberately."],
        "Pick something that has been bothering you and that you've been blaming on someone else. Write one sentence starting with 'What I can do about it is…' and do that one thing this week."],
      ["Pick better values",
        "Values you control hold up. Values that depend on other people collapse.",
        ["Your values are the yardstick you use to measure yourself and your life. If your values are bad, everything feels bad, even when things are going well. Manson describes bad values as those that are based on pleasure, external approval or things outside your control: being liked by everyone, always feeling good, being the best.",
         "Good values are reality-based, socially constructive and within your control. Honesty, curiosity, standing up for yourself, helping others and humility are good examples. You can live them today, no matter what happens around you.",
         "Many people's problems aren't really problems. They're symptoms of measuring themselves with the wrong ruler."],
        "Write down what you currently judge your days by. Circle anything that depends on other people's reactions and replace it with something you can do yourself."],
      ["Hold your beliefs loosely",
        "Assume you're partly wrong. That's how you grow instead of defending old mistakes.",
        ["We tend to treat our beliefs as facts, especially beliefs about ourselves: 'I'm not a morning person', 'I'm bad with money'. Many of these were formed on flimsy evidence and then defended for years because changing them feels threatening.",
         "Growth is really a process of being slightly less wrong over time. Every belief you have today will probably look naive to you in ten years, just as your beliefs from ten years ago do now.",
         "Manson calls this his law of avoidance: the more something threatens your identity, the more you will avoid it. The fix is to hold a smaller, looser identity, so that new information doesn't feel like an attack."],
        "Pick one thing you believe about yourself that holds you back. Look for three pieces of evidence against it."],
      ["Failure is the way forward",
        "You can't get good at something without first being bad at it.",
        ["Improvement at anything is built on thousands of tiny failures. The people who are great at something have failed at it more times than beginners have even tried. Avoiding failure therefore means avoiding improvement.",
         "Manson's 'do something' principle: action is not only the result of motivation, it's also the cause of it. Waiting until you feel motivated often means waiting forever. Doing even a tiny piece of the task produces the motivation to continue.",
         "Pain is part of the process. If you only ever do what is comfortable, you will only ever be what you already are."],
        "When you're stuck on something today, do the smallest possible version of it for two minutes. Let the action create the motivation."],
      ["Commitment is a kind of freedom",
        "Saying no to most options lets you go deep on a few, and depth is where the rewards are.",
        ["Having endless options feels like freedom, but it often leads to anxiety and shallow experiences. When you can go anywhere, do anything or date anyone, you never commit enough to get the deeper rewards those things offer.",
         "Rejecting things is essential. If you never say no, you don't really stand for anything. Your values are defined as much by what you turn down as by what you pursue.",
         "The same goes for your 66 days. The streak works because it closes off the option of skipping. That constraint is what builds the person you're trying to become."],
        "Name one thing you'll deliberately say no to for the rest of this program so you can go deeper on something that matters more."]
    ]
  },
  {
    id: "dopamine", title: "Dopamine Detox", short: "Dopamine Detox", author: "Thibaut Meurisse", tint: "violet",
    gist: "When your day is packed with cheap, instant rewards, meaningful work feels dull. Lower the stimulation and focus comes back.",
    ideas: [
      ["Overstimulation kills motivation",
        "Easy rewards make slow, valuable work feel boring by comparison.",
        ["Meurisse's core point is about contrast. If your baseline is constant novelty from phones, video, sugar and notifications, anything that doesn't offer the same instant hit feels painful. Studying, training or deep work haven't changed. Your threshold for 'interesting' has.",
         "That's why you can sit down to work and find yourself on your phone ten minutes later without deciding to. Your brain is simply going to the most stimulating option available.",
         "The goal isn't to remove all pleasure. It's to make sure the hard, important tasks aren't competing with something far more stimulating a few centimetres away."],
        "For one day, notice every time you reach for your phone without a clear reason. Just count them. Awareness comes before change."],
      ["Reset with a detox day",
        "Spend a day cutting your biggest stimulants. The boredom is the point.",
        ["The book suggests a 24 to 48 hour reset where you remove the most stimulating activities: social media, video, games, junk food and sometimes even music. You fill the time with low-stimulation things: walking, reading, journaling, tidying, thinking.",
         "The first few hours often feel restless and uncomfortable. That discomfort shows how dependent you had become. Many people find that by the end of the day, ordinary things like a book or a conversation feel noticeably more engaging.",
         "It's not a permanent lifestyle. Think of it as recalibrating your settings so everyday focus becomes easier again."],
        "Schedule a half-day this weekend with no phone, no screens and no snacks. Walk, read or write instead, and note how your focus feels afterwards."],
      ["Find your triggers",
        "You can only remove distractions you've actually noticed.",
        ["Distractions rarely feel like decisions. They're automatic responses to triggers: boredom, a hard task, a notification, anxiety, tiredness. Meurisse suggests keeping a short log of when you get pulled off task and what was happening just before.",
         "Patterns show up quickly. Maybe you always check your phone the moment a task gets difficult, or when you first sit down, or after a meal. Once you know the trigger, you can plan a different response in advance.",
         "Separate high-stimulation activities (instant, addictive), medium ones (useful but can spiral, like email) and low ones (focused, rewarding later). The aim is to move more of your day to the low end."],
        "Keep a note today titled 'Pulled away'. Each time you get distracted, write the time and what you were feeling right before."],
      ["Add friction to bad habits",
        "Make distraction slightly harder than doing the work.",
        ["Willpower is unreliable, so change the environment. Log out of apps, move them off your home screen, delete the ones that eat the most time, leave your phone in another room while you work, and turn off every notification that isn't from a real person.",
         "Even a ten-second barrier makes a big difference, because many distracting behaviours are impulses that fade if they aren't satisfied immediately. When the easiest action becomes the right one, you need far less discipline.",
         "The same principle works in reverse: remove friction from good habits. Put the book on your pillow and the gym bag by the door."],
        "Move your three most distracting apps into a folder on your last home screen page, and turn off their notifications."],
      ["Do the hardest task first",
        "Tackle your most important work before cheap rewards raise your stimulation level.",
        ["Your stimulation level usually rises through the day. If you start with messages, news and social media, your brain is already over-stimulated by the time you reach the important work, and that work will feel even harder.",
         "Starting with the hardest, most important task means you face it while your baseline is low and your willpower fresh. Everything after it feels easier, and the day already counts as a win.",
         "Meurisse recommends a simple morning routine without screens for the first 30 to 60 minutes. It protects this window."],
        "Tomorrow, don't open any app until you've done 20 minutes on your most important task."],
      ["Warm up into deep work",
        "Start with a small, easy piece of the task, and momentum will carry you into focus.",
        ["Big tasks feel threatening, so we avoid them. The trick is to lower the entry cost. Instead of 'write the report', begin with 'open the document and write the headings'. Instead of 'train', begin with 'put on training clothes'.",
         "Once you've started, the task becomes less abstract and less scary. Focus tends to build over the first ten to fifteen minutes. The warm-up simply gets you through the part where quitting is most tempting.",
         "Pair this with the Focus timer in the Everyday tab: commit to only the first five minutes and see whether you keep going."],
        "Break your next dreaded task into a first step that takes under five minutes, and do just that."],
      ["Make it a routine, not an event",
        "Regular low-stimulation blocks keep focus as your default.",
        ["A one-off detox gives you a boost, but old habits creep back. The lasting results come from building low-stimulation habits into your normal week: screen-free mornings, a phone-free evening hour, one day a week with no social media.",
         "Think of it like diet and exercise. One healthy day doesn't change much, but a consistent pattern reshapes your baseline.",
         "Track it the same way you track other habits. A small daily rule you keep is worth more than a dramatic plan you abandon."],
        "Pick one standing rule, like 'no phone in bed' or 'no screens before 8 am', and add it as a daily task."],
      ["Learn to enjoy slow rewards",
        "Reading, training and learning pay off quietly. Train yourself to notice those rewards.",
        ["Activities with delayed rewards feel worse in the moment than instant pleasures, but they compound. Fitness, skill and knowledge all grow slowly, then suddenly.",
         "Part of the detox is retraining what feels rewarding. Notice the calm after a long walk, the clarity after writing, the satisfaction of finishing a hard session. Over time, these become things you genuinely look forward to.",
         "Your journal helps here. Writing down small wins makes slow progress visible, which your brain will treat as a reward."],
        "At the end of today, write one sentence in your journal about a slow reward you noticed."]
    ]
  },
  {
    id: "rules", title: "12 Rules for Life", short: "12 Rules", author: "Jordan B. Peterson", tint: "blue",
    gist: "Life involves suffering, and the best answer to it is meaning found by taking on responsibility. Start by putting your own life in order.",
    ideas: [
      ["Stand up straight",
        "Posture and confidence feed each other. Face challenges openly.",
        ["Peterson opens with lobsters, which have ancient status systems influenced by serotonin. A lobster that wins fights stands taller and is more likely to win the next one. Humans have similar systems. How you carry yourself affects how others treat you and how you feel about yourself.",
         "Standing up straight is a metaphor as much as a physical instruction. It means accepting the responsibilities of life with open eyes, rather than cowering from them.",
         "Small changes in posture and eye contact can shift how people respond to you, and that feedback builds real confidence over time."],
        "Today, walk, sit and speak as if you've already accepted whatever challenge is in front of you. Notice whether it changes how you feel."],
      ["Treat yourself like someone you're responsible for",
        "Look after yourself the way you'd look after someone you were responsible for helping.",
        ["Peterson notes that people are often better at making sure their pet takes its medication than at taking their own. Many of us don't really believe we deserve care, so we neglect sleep, health and our own goals.",
         "The idea is to act as your own guardian. Ask what would actually be good for you, not what feels pleasant in the moment. A good carer sets rules, encourages growth and doesn't indulge every whim.",
         "This includes having a direction. Someone you cared about would need a meaningful aim, so give yourself one."],
        "Ask yourself: if I were in charge of someone exactly like me, what would I make sure they did tomorrow? Then do it."],
      ["Choose friends who want the best for you",
        "Spend time with people who lift you up, not those who drag you down.",
        ["The people you spend time with shape your habits and expectations. Peterson warns against surrounding yourself with people who don't want you to improve, and against the idea that you must always rescue someone who isn't willing to help themselves.",
         "Good friends are pleased when you get better and will call you out when you're heading in the wrong direction. That's not always comfortable, but it's what you need.",
         "It's also a responsibility in reverse: be that kind of friend for others."],
        "Think about who you spent the most time with this week. Did they make it easier or harder to be your best self?"],
      ["Compare yourself to who you were yesterday",
        "Measure progress against your own past, not someone else's highlight reel.",
        ["There's always someone better than you at something, and modern life puts them in your feed all day. Comparing yourself to them is demoralising and not very useful, because you don't know their whole story.",
         "A more useful comparison is with your past self. Are you a little better than yesterday? Small improvements, repeated daily, add up to a huge difference over time.",
         "Peterson suggests negotiating with yourself: ask what small thing you could do today to make life slightly better, and do it."],
        "In tonight's journal entry, write one way you're better than you were a month ago."],
      ["Set your house in order before criticising the world",
        "Get your own life organised before blaming everything around you.",
        ["When life feels chaotic, it's tempting to blame the system, society or other people. Peterson argues that we should start closer to home: fix what's within reach, clean up your room, keep your commitments, stop doing the things you know are wrong.",
         "This isn't saying the world has no problems. It's saying you'll be in a much better position to address bigger issues once you've shown you can handle the small ones.",
         "It also builds momentum. Order in your own space creates a sense of control that spreads to other parts of your life."],
        "Spend 15 minutes putting one physical space in order today: your desk, room or car."],
      ["Pursue what is meaningful, not what is expedient",
        "Comfort fades. Meaning comes from taking on responsibility and doing hard, worthwhile things.",
        ["Expediency means doing what's easiest right now to avoid discomfort. Meaning comes from sacrificing short-term comfort for something more valuable later. Peterson connects this to the discovery of the future: people learned they could bargain with it by giving something up today.",
         "Meaning is the antidote to suffering. It doesn't remove hardship, but it makes it bearable and worthwhile.",
         "Picking the harder, more meaningful option repeatedly is how character forms."],
        "Next time you choose between an easy option and a meaningful one, pause and choose the meaningful one deliberately."],
      ["Tell the truth, or at least don't lie",
        "Honesty keeps your life on solid ground and makes your words carry weight.",
        ["Lies, including small ones and lies to yourself, gradually distort your view of reality. You make decisions based on a picture that isn't accurate, and things go wrong in ways you can't understand.",
         "Telling the truth is often uncomfortable, but it keeps your relationships and plans grounded in what's real. Over time, people learn they can trust what you say.",
         "Peterson also means not acting out a lie: pretending to want things you don't, or living by values you don't believe in."],
        "Notice one small lie you tell out of habit, even something like 'I'm fine'. Replace it with something true today."],
      ["Assume the other person knows something you don't",
        "Listen properly. Real conversation changes you.",
        ["Most conversations are two people waiting to talk. Peterson suggests genuinely listening, as if the other person might teach you something important. Often they will.",
         "One practical method is to summarise what the other person said before you respond, to their satisfaction. It forces you to understand their view and shows respect.",
         "Good listening also helps people think more clearly. Many problems are solved just by talking them through with someone who pays attention."],
        "In your next real conversation, ask one follow-up question before sharing your own view."]
    ]
  },
  {
    id: "power", title: "The 48 Laws of Power", short: "48 Laws", author: "Robert Greene", tint: "red",
    gist: "Power works in patterns that repeat throughout history. Know them so you can use them wisely, and so you can spot them being used on you.",
    ideas: [
      ["Never outshine the master",
        "Help the people above you look good. Showing them up can make you a threat.",
        ["Greene's first law comes from court politics, but it still applies at work and elsewhere. People in charge often feel insecure. If you make them look foolish or openly show you're more talented, they may see you as a threat rather than an asset.",
         "This doesn't mean hiding your ability. It means sharing credit, letting your talents serve the people above you and waiting until you have your own position before putting yourself centre stage.",
         "Read it as advice about timing and ego, not about shrinking yourself."],
        "Next time you contribute a good idea, frame it so your team or lead benefits from it too."],
      ["Say less than necessary",
        "Talking too much reveals your hand. Restraint reads as confidence.",
        ["The more you say, the more likely you are to say something foolish, give away your plans or commit to something you regret. People who speak less appear more mysterious and powerful, and their words carry more weight.",
         "This is especially true in tense moments: negotiations, arguments or when you're being criticised. Silence gives the other person room to reveal more.",
         "It also saves you from over-explaining yourself, which often sounds defensive."],
        "In your next disagreement, make your point once, clearly, and then stop talking."],
      ["Guard your reputation with your life",
        "Reputation opens doors before you arrive. Build it and protect it.",
        ["Reputation is the story people tell about you when you're not in the room. A strong reputation can win situations before you do anything, and a damaged one is extremely hard to repair.",
         "Greene suggests building a reputation for one quality, like reliability, generosity or excellence, and making it clear and consistent.",
         "The simplest way to build a good reputation is to do what you said you'd do, every time."],
        "Choose one quality you want to be known for, and do one thing this week that proves it."],
      ["Win through actions, not arguments",
        "Winning an argument often loses the relationship. Results persuade better.",
        ["Arguments make people defensive. Even if you win, the other person may resent you and resist quietly afterwards. Showing people something works tends to persuade far more than telling them.",
         "Greene's point is that demonstration beats debate. If you think a method is better, use it and let the results speak.",
         "This is also a relief: you don't have to convince everyone. You just have to get results."],
        "Instead of arguing for a change you want, run a small experiment and show the outcome."],
      ["Make yourself hard to replace",
        "Become valuable enough that people need you around.",
        ["Greene frames it as making others depend on you. A healthier way to read it: develop skills and relationships that make you genuinely valuable. The more useful and hard to replace you are, the more security and options you have.",
         "That means going deep on skills most people won't put in the hours to learn, and becoming the person others trust to get things done.",
         "Independence also matters. The more you rely on a single person or place, the less power you have."],
        "Name one skill that would make you noticeably more valuable, and schedule practice for it this week."],
      ["Stay formless and adaptable",
        "Rigid people are predictable. People who can adjust are hard to beat.",
        ["Greene's final law says that by not committing to one fixed shape, you make yourself hard to attack. The world changes constantly, so people who cling to one approach get left behind.",
         "This connects with The Art of War's idea of being like water. Stay clear on your goals but flexible about how you reach them.",
         "Adaptability is a skill: try new methods, get feedback quickly and be willing to drop what isn't working."],
        "Identify one habit or method that isn't working and change your approach to it this week."],
      ["Know when to stop",
        "Don't push past a win. Overreaching after success is how people lose what they gained.",
        ["Success is intoxicating. After a win, people often get overconfident, take bigger risks and ignore warning signs. Greene points to many figures in history who lost everything by not stopping at the right time.",
         "Setting a clear goal before you start helps. When you reach it, pause, secure the win and reassess before pushing on.",
         "The same applies to training: stop a set before form breaks down rather than grinding into injury."],
        "When you hit your target today, stop. Don't add 'just one more' out of excitement."],
      ["Use the laws as defence too",
        "Many of the laws describe tactics others use on you. Knowing them helps you spot manipulation.",
        ["The 48 Laws is often criticised as a manual for manipulation. It's more useful as a guide to recognising it. Flattery, strategic silence, playing on your insecurities and hidden agendas are all easier to resist once you can name them.",
         "Greene's historical stories show how people have been exploited by those who understood power better than they did.",
         "Understanding power doesn't mean you have to become ruthless. It means you won't be naive."],
        "Think of a time someone persuaded you into something you regretted. Which tactic did they use?"]
    ]
  },
  {
    id: "prince", title: "The Prince", short: "The Prince", author: "Niccolò Machiavelli", tint: "indigo",
    gist: "A 500-year-old handbook on how power is really won and kept. Read it as a study of people and consequences, not a licence to be cruel.",
    ideas: [
      ["See things as they are",
        "Deal with people as they actually behave, not as they ought to.",
        ["Machiavelli broke with the writers of his time, who described ideal rulers in imaginary states. He wanted to write about how things really work. A person who acts as if everyone is good will be ruined among the many who are not.",
         "The practical lesson is to plan around reality. People are inconsistent, self-interested and influenced by circumstance, including you. A plan that only works if everyone behaves perfectly is not a plan.",
         "This isn't cynicism for its own sake. Clear sight is what lets you protect yourself and the people who depend on you."],
        "Take one plan you're relying on. Ask what happens if the people involved act in their own interest instead of yours, and adjust it."],
      ["Fortune and ability",
        "Luck controls about half of what happens. Your ability decides the rest.",
        ["Machiavelli compares fortune to a flooding river. You can't stop the flood, but in calm weather you can build banks and dams so that, when it comes, the damage is limited.",
         "His word for the other half is virtù: not virtue in the moral sense, but capability, energy and readiness. People with virtù make use of whatever chance gives them. People without it are swept along.",
         "Preparation in quiet times is the whole game. That's what your daily tasks are: dams built before the flood."],
        "Name one area where you're relying on luck. Build one small 'dam' for it this week: a buffer, a backup or a skill."],
      ["Build on your own foundations",
        "What you earn through your own effort lasts. What others hand you can be taken back.",
        ["Rulers who rose through luck or other people's favour, Machiavelli notes, gained their position easily but struggled to keep it. Those who rose through their own ability found it hard at first, then held on securely.",
         "The same is true of confidence, skill and reputation. Anything that depends on someone else's goodwill is fragile.",
         "Slow, self-made progress feels less exciting, but no one can revoke it."],
        "Pick one thing you currently depend on someone else for, and take one step towards being able to do it yourself."],
      ["Feared or loved",
        "Ideally both. If you must choose, reliability beats being liked.",
        ["Machiavelli's most famous argument is that it is safer to be feared than loved if you cannot be both, because love is broken whenever it suits people, while fear of consequences holds steady. Crucially, he adds that you must never become hated.",
         "A modern reading: being liked is pleasant but unstable. Being known as someone whose word has consequences, who does what they say and holds firm boundaries, earns respect that lasts.",
         "You can be warm and still be someone people don't take lightly."],
        "Set one clear boundary this week and hold it calmly, without apologising for it."],
      ["Appearance matters",
        "Most people judge by what they see. Few look closer.",
        ["Machiavelli observes that everyone sees what you appear to be, but very few experience who you really are. Reputation is built largely on appearances and results.",
         "The takeaway isn't to be fake. It's to be deliberate about what you show. Quiet competence, calm under pressure and keeping your plans to yourself until they're ready all shape how you're perceived.",
         "It also works in reverse: be careful judging others only by what they choose to show you."],
        "Before your next important conversation, decide what impression you want to leave, then let your actions carry it rather than your words."],
      ["Act decisively",
        "Half-measures satisfy no one. Commit fully or not at all.",
        ["Machiavelli repeatedly criticises indecision. Rulers who tried to stay neutral or took the middle path often made enemies of both sides.",
         "In everyday life, hesitation has its own cost. Endlessly weighing options, half-committing to a plan or delaying a hard conversation usually makes things worse.",
         "Gather the information you need, decide, then act with conviction. You can adjust later, but you can't steer a car that isn't moving."],
        "Make one decision today that you've been putting off, and act on it within the hour."],
      ["Do hard things all at once",
        "Deliver bad news in one go. Spread good things out over time.",
        ["Machiavelli advises that unpleasant measures should be carried out all at once, so their sting is felt briefly, while benefits should be given little by little so they are appreciated more.",
         "Applied to yourself: rip off the plaster. Tackle the hardest part of a change in one decisive block rather than dragging it out. Then reward yourself in small, regular doses.",
         "It's the same logic as doing your hardest task first thing in the morning."],
        "Batch the most unpleasant item on your list into one focused session today and get it done in one go."],
      ["Stay adaptable",
        "The approach that won yesterday can lose tomorrow. Change with the times.",
        ["Machiavelli notes that people tend to succeed when their natural style suits the times, and fail when the times change but they don't. The cautious do well in calm periods, the bold in turbulent ones.",
         "The rare advantage is being able to switch: patient when patience pays, bold when boldness is needed.",
         "Notice when your usual approach has stopped working, and be willing to try the opposite."],
        "Think of something where your usual approach isn't working. Try the opposite style for one week."]
    ]
  },
  {
    id: "war", title: "The Art of War", short: "Art of War", author: "Sun Tzu", tint: "teal",
    gist: "Written about warfare 2,500 years ago, it's really about strategy: prepare well, know the ground and win with as little conflict as possible.",
    ideas: [
      ["Know yourself and your opponent",
        "Understand your strengths and weaknesses and theirs, and you can face anything calmly.",
        ["Sun Tzu's best-known idea: if you know both yourself and your opponent, you need not fear the outcome. If you only know yourself, you'll win some and lose some. If you know neither, you'll lose.",
         "In daily life, the 'opponent' is often a challenge rather than a person: an exam, a fitness goal, a bad habit. Understanding exactly what you're up against, and your own tendencies, is most of the battle.",
         "Honest self-knowledge is the harder half. It requires admitting weaknesses as well as strengths."],
        "For your biggest current challenge, list three of your strengths and three weaknesses that matter for it."],
      ["Win before the battle begins",
        "Preparation decides most outcomes. Only fight when the odds are already in your favour.",
        ["Sun Tzu argues that victorious armies win first and then go to war, while defeated armies go to war and then look for a way to win. The work is done in preparation: planning, training and positioning.",
         "Applied to your goals, this means setting up the conditions for success before relying on effort in the moment: sleep well before an exam, prepare meals before a busy week, lay out training gear the night before.",
         "When the moment comes, you're simply carrying out a plan that was already likely to succeed."],
        "Tonight, spend ten minutes setting up tomorrow so the important things are easy to do."],
      ["The best victory needs no fight",
        "Getting the result without conflict is the highest skill.",
        ["Sun Tzu considered winning a hundred battles less impressive than subduing the enemy without fighting at all. Conflict is costly, even when you win.",
         "In everyday life, this means solving problems before they escalate, finding outcomes where both sides benefit and not treating every disagreement as a battle to be won.",
         "Often the smartest move is to make a conflict unnecessary."],
        "Think of a current conflict. Is there a way to get what you need without a confrontation?"],
      ["Attack weakness, avoid strength",
        "Don't pour effort into the hardest wall. Find where a little effort goes a long way.",
        ["Water flows around rocks rather than through them. Sun Tzu advises avoiding the opponent's strongest points and focusing on where they are weak.",
         "For personal goals, this means finding leverage. If you want to get fit, the weakest point in your resistance might be a ten-minute morning routine rather than a gruelling gym plan. Start where progress is easiest and build from there.",
         "It also means knowing when not to fight: some battles aren't worth the cost."],
        "Look at a goal you're stuck on and find the easiest point of entry. Start there."],
      ["Speed matters",
        "Long campaigns drain everyone. Once you commit, act decisively.",
        ["Sun Tzu warns that no country has ever benefited from a long war. Extended efforts consume resources and morale.",
         "In personal terms: when you decide to do something, do it quickly and fully rather than half-heartedly for months. Long, drawn-out projects often lose momentum.",
         "Speed doesn't mean rushing preparation. It means that once you've prepared, you act without hesitating."],
        "Pick one task you've been dragging out and finish it in one focused session this week."],
      ["Be like water",
        "Water adapts to the ground. Adjust your plan to conditions instead of forcing it.",
        ["Sun Tzu compared an army to water, which has no fixed shape and flows around obstacles to lower ground. A good strategist adapts tactics to the situation rather than following a rigid plan.",
         "Plans are useful, but reality rarely goes to plan. The skill is to hold your goal steady while changing your methods as conditions change.",
         "If your schedule falls apart one day, adapt: a shorter workout, a quick journal entry. Don't abandon the streak."],
        "When today doesn't go to plan, ask what the smallest adapted version of your goal looks like, and do that."],
      ["Choose your terrain",
        "Where and when you compete matters as much as how.",
        ["Sun Tzu devotes whole chapters to terrain: high ground, narrow passes, open plains. The ground you fight on can decide the outcome before the battle starts.",
         "In modern life, terrain is your environment. Work somewhere distractions can't reach you. Train at a time of day when you have energy. Have difficult conversations in calm settings.",
         "Picking the right environment can make hard things feel much easier."],
        "Identify the setting where you do your best work, and schedule your hardest task there."],
      ["Discipline beats bravado",
        "Clear structure, training and steady leadership outlast raw courage.",
        ["Sun Tzu emphasises discipline, clear orders and well-trained troops. Bravery helps, but an undisciplined army falls apart under pressure.",
         "The same is true of personal goals. Motivation comes and goes, but routines and habits hold up when motivation disappears.",
         "Your daily tasks in Ascend are your training drills. Consistency is what makes you reliable when it counts."],
        "Commit to completing today's minimum even if you don't feel like it. Discipline is built on days like that."]
    ]
  },
  {
    id: "atomic", title: "Atomic Habits", short: "Atomic Habits", author: "James Clear", tint: "lime",
    gist: "Big results come from small habits repeated every day. Make good habits easy and bad habits hard, and focus on who you're becoming.",
    ideas: [
      ["Get one percent better",
        "Tiny improvements look like nothing day to day and huge over a year.",
        ["If you get one percent better each day for a year, you end up far better than when you started. Get one percent worse and you decline towards zero. Habits are the compound interest of self-improvement.",
         "The problem is that small changes are invisible early on. Clear calls this the plateau of latent potential: you put in work without seeing results, then progress suddenly shows up.",
         "Don't judge habits by immediate results. Judge them by the direction they're taking you."],
        "Pick one daily task and make it one percent better tomorrow, like one extra rep or five more minutes."],
      ["Systems beat goals",
        "Goals set direction, but your daily system decides whether you get there.",
        ["Winners and losers often have the same goals. The difference is in their systems: the daily processes that lead to results.",
         "Goals are also temporary. Once you reach them, you often stop. Systems keep you improving.",
         "Clear suggests falling in love with the process. The results will follow."],
        "Write down the daily system behind your main goal: exactly what you do, when and where."],
      ["Change your identity",
        "Aim to become the kind of person who does the thing. Each repetition is a vote.",
        ["There are three levels of change: outcomes (what you get), processes (what you do) and identity (what you believe about yourself). Lasting change starts with identity.",
         "Instead of 'I want to run a marathon', think 'I'm a runner'. Every time you run, you cast a vote for that identity. You don't need every vote, just a majority.",
         "Your habits then feel like expressions of who you are rather than chores."],
        "Complete this sentence and keep it in your journal: 'I am the type of person who…'"],
      ["Make it obvious",
        "Put cues where you'll see them.",
        ["Every habit starts with a cue. If the cue is hidden, the habit won't happen. Put a water bottle on your desk, place a book on your pillow, lay out gym clothes the night before.",
         "Clear also recommends implementation intentions: 'I will [habit] at [time] in [place].' This removes the question of when and where.",
         "Habit stacking helps too: 'After I [current habit], I will [new habit].'"],
        "Write one habit stack: 'After I ____, I will ____.' Try it tomorrow."],
      ["Make it attractive",
        "Pair a habit you need with something you enjoy.",
        ["We're more likely to do things we look forward to. Temptation bundling pairs a habit you need to do with one you want to do: only listen to your favourite podcast while training, for example.",
         "Your environment and the people around you also shape what feels attractive. Joining groups where your desired behaviour is normal makes it easier.",
         "Anticipation drives motivation, so make the lead-up enjoyable."],
        "Bundle one habit with something you enjoy this week."],
      ["Make it easy",
        "Shrink the habit until starting takes two minutes.",
        ["The two-minute rule: scale any new habit down to something that takes two minutes. 'Read before bed' becomes 'read one page'. 'Train' becomes 'put on training clothes'.",
         "The point is to master showing up. A habit must be established before it can be improved.",
         "Reducing friction matters too. The fewer steps between you and the habit, the more likely it happens."],
        "Take one habit you keep skipping and write its two-minute version. Do only that tomorrow."],
      ["Make it satisfying",
        "Reward yourself right away. Tracking a streak is a reward in itself.",
        ["What is immediately rewarded is repeated. The problem with good habits is that their rewards are delayed. So add an immediate reward: tick a box, see a streak grow, earn XP.",
         "Habit tracking works because it makes progress visible. It's why Ascend shows streaks, XP and levels.",
         "Clear warns not to break the chain, but also not to obsess over perfection."],
        "Notice the satisfaction of ticking off today's tasks. That feeling is the reward that keeps the habit going."],
      ["Never miss twice",
        "Missing once is an accident. Missing twice starts a new habit.",
        ["Everyone slips up. The key is how quickly you recover. Missing one day has little impact on long-term progress, but missing two starts a new pattern.",
         "Clear suggests having a plan for bad days: a minimum version of the habit you can do even when you're tired or busy.",
         "This is why Ascend uses a daily minimum: it gives you a floor to hit on the worst days."],
        "Decide now what your 'bad day minimum' is for each daily task."]
    ]
  },
  {
    id: "goggins", title: "Can't Hurt Me", short: "Can't Hurt Me", author: "David Goggins", tint: "red",
    gist: "Goggins went from a hard childhood and poor health to Navy SEAL and ultra-endurance athlete. His message: most people use a fraction of their potential.",
    ideas: [
      ["The 40% rule",
        "When your mind says you're done, you've usually used only a fraction of what you have.",
        ["Goggins argues that when your mind tells you you're exhausted, you're typically only about 40% of the way to your actual limit. The brain is protective and wants you to stop well before real danger.",
         "Learning to push past that first 'I'm done' signal opens up capacity you didn't know you had.",
         "This isn't about ignoring genuine injury. It's about recognising that the first wave of discomfort is not the limit."],
        "In your next workout, when you want to stop, do one more set or one more minute. Notice that you can."],
      ["Callous your mind",
        "Do hard things on purpose, so you're ready when life gets hard on its own.",
        ["Just as hands grow calluses from repeated friction, your mind toughens through repeated discomfort. Goggins seeks out hard things deliberately: early runs, cold, difficult challenges.",
         "The more discomfort you face voluntarily, the less power it has over you when it arrives uninvited.",
         "Cold showers, early mornings and hard training sessions in your task list are small daily calluses."],
        "Choose one uncomfortable thing to do today that you'd normally avoid."],
      ["The cookie jar",
        "Keep a list of hard things you've already survived. Draw on it when you want to quit.",
        ["Goggins keeps a mental 'cookie jar' of past victories and hardships he got through. When he's struggling, he reaches in and reminds himself of what he's already overcome.",
         "This builds evidence that you're capable of handling difficulty. It's hard to believe you can't do something when you have a list of things you've already done.",
         "Your journal can be your cookie jar."],
        "Write down five hard things you've already got through. Reread the list the next time you want to give up."],
      ["The accountability mirror",
        "Be brutally honest with yourself about where you're falling short.",
        ["Goggins used sticky notes on his mirror to confront his weaknesses and set goals. He didn't lie to himself about his situation.",
         "Honesty is uncomfortable, but it's the only way to fix what's wrong. You can't change what you won't admit.",
         "Once the truth is on the mirror, set specific goals to address each point."],
        "Write one honest note about something you need to improve and put it where you'll see it every morning."],
      ["Own your past",
        "What happened to you shapes you, but it doesn't get to decide what you do next.",
        ["Goggins had an abusive childhood, faced racism and struggled with learning difficulties. Instead of letting it define him, he took ownership of his story and used it as fuel.",
         "Owning your past means accepting it fully, including the painful parts, then choosing what to do with it.",
         "It's a choice to stop being a victim of your story and start being its author."],
        "Think of something from your past that still holds you back. Write how it could become fuel instead."],
      ["Stay hard when it's easy",
        "Keep the discipline going after a win. Complacency undoes progress quickly.",
        ["After success, it's tempting to relax. Goggins warns that comfort is the enemy of progress. The moment you coast, you start slipping back.",
         "Staying hard doesn't mean never resting. It means not letting a win become an excuse to drop your standards.",
         "This applies directly to streaks: day 40 needs the same effort as day 4."],
        "After a good day, keep tomorrow's standard exactly the same. Don't reward yourself by lowering it."],
      ["Audit your time",
        "Map where your hours actually go. You probably have more time than you think.",
        ["Goggins recommends tracking your time for a week to see where it really goes. Most people find hours lost to scrolling, TV and unplanned downtime.",
         "Once you see your time clearly, you can schedule the important things and protect them.",
         "Time audits often reveal that 'I don't have time' actually means 'it's not a priority'."],
        "For one day, jot down what you did each hour. Look for at least 30 minutes you could reclaim."],
      ["Chase uncommon",
        "Doing what everyone else does gets you what everyone else gets.",
        ["Goggins talks about becoming uncommon among the uncommon: not stopping at being good but continuing to push when others stop.",
         "It isn't about comparing yourself to others. It's about refusing to settle for less than you're capable of.",
         "Consistency when no one is watching is what separates uncommon results from ordinary ones."],
        "Pick one area where you've been settling for average. Set a standard that would genuinely stretch you."]
    ]
  },
  {
    id: "meditations", title: "Meditations", short: "Meditations", author: "Marcus Aurelius", tint: "ice",
    gist: "The private notes of a Roman emperor reminding himself how to live well: control your mind, do your duty and accept what you can't change.",
    ideas: [
      ["Focus on what you control",
        "Your choices and responses are yours. Other people and events are not.",
        ["The central Stoic idea: some things are up to us (our judgements, intentions and actions) and some are not (other people, reputation, outcomes, the weather). Suffering often comes from treating the second group as if it were the first.",
         "Marcus reminded himself constantly to put his energy into his own conduct and let go of the rest.",
         "This isn't passive. It concentrates your effort where it can actually make a difference."],
        "When something frustrates you today, ask: is this within my control? If not, let it go. If so, act."],
      ["Your view is what hurts",
        "Events are neutral. The story you tell about them makes them unbearable.",
        ["Marcus wrote that if you're distressed by something external, the pain isn't from the thing itself but from your judgement of it, and you can change that judgement.",
         "An insult, a delay or a setback only has the meaning you give it. That doesn't make hard things disappear, but it gives you room to choose your response.",
         "Separating what happened from the story you're telling yourself about it is a powerful habit."],
        "Next time you're upset, write the plain facts of what happened, then the story you added. Notice the gap."],
      ["Get up and do your work",
        "Rising to do your part is what you're here for. Comfort isn't the goal.",
        ["Marcus wrote a note to himself about not wanting to get out of bed. His answer: you were made to act, to do the work of a human being, not to lie in comfort.",
         "Even an emperor struggled with motivation. What mattered was acting anyway.",
         "Your wake time and daily tasks are this principle in practice."],
        "Tomorrow morning, when you want to stay in bed, remind yourself what you're getting up to do, and get up."],
      ["The obstacle becomes the path",
        "What stands in the way becomes the way.",
        ["Marcus observed that the mind adapts and turns obstacles to its purpose. A setback can become a chance to practise patience, courage or creativity.",
         "Every difficulty is an opportunity to develop a virtue. A rude person gives you practice in patience. A setback gives you practice in resilience.",
         "This idea later inspired Ryan Holiday's The Obstacle Is the Way."],
        "Take today's biggest obstacle and ask: which quality could this help me build?"],
      ["Remember you will die",
        "Life is short. Let that make you act well today, not someday.",
        ["Marcus often reflected on death, not to be morbid but to stay focused. Knowing life is short cuts through trivial worries and procrastination.",
         "If today were one of your last, would you spend it the way you're planning to? Not every day can be profound, but this question helps you drop what doesn't matter.",
         "It also encourages gratitude for what you have now."],
        "Tonight, write one thing you'd regret not doing if your time were short. Plan a step towards it."],
      ["Don't live for others' opinions",
        "Worrying what people think of you steals time from being good.",
        ["Marcus noted how much time people waste thinking about what others are doing or saying, time that could go into their own improvement.",
         "Other people's opinions are outside your control. Your character is inside it.",
         "Do what's right and let others think what they want."],
        "Notice one decision you're making to impress someone. Ask what you'd do if nobody would ever know."],
      ["Stop arguing about what a good person is",
        "Just be one.",
        ["It's easy to talk about ideals. Marcus reminded himself to stop theorising and start acting.",
         "Goodness is proven in small daily actions: patience, honesty, doing your job well, treating people fairly.",
         "Knowledge without practice is useless."],
        "Pick one virtue today, like patience, honesty or kindness, and practise it deliberately at least three times."],
      ["Take the view from above",
        "Zoom out. Most things that feel huge right now are tiny against the scale of time.",
        ["Marcus practised imagining the world from high above: cities, crowds and events all shrink. Things that feel enormous look small against the scale of the universe and history.",
         "This perspective calms anxiety and anger. Few of today's worries will matter in ten years.",
         "It's also a reminder of our shared humanity: everyone is dealing with their own struggles."],
        "When you're stressed today, take a minute to picture the situation from far above and ask if it'll matter in a year."]
    ]
  },
  {
    id: "deepwork", title: "Deep Work", short: "Deep Work", author: "Cal Newport", tint: "indigo",
    gist: "The ability to focus without distraction on hard tasks is rare and valuable. Those who build it will do better in almost any field.",
    ideas: [
      ["Depth is a superpower",
        "Focused work on hard problems is becoming rare, which makes it more valuable.",
        ["Newport defines deep work as focused, distraction-free effort that pushes your ability to its limit. It produces new value and improves your skills.",
         "As more people are constantly connected and distracted, the ability to go deep becomes a competitive advantage. Those who can learn hard things quickly and produce excellent work will stand out.",
         "It's a skill, not a personality trait. You can train it."],
        "Schedule one 50-minute deep work block this week using the timer in the Everyday tab."],
      ["Shallow work fills the day",
        "Email, messages and busywork feel productive but rarely move anything forward.",
        ["Shallow work is logistical, low-demand and easy to replicate: replying to messages, admin, meetings. It's necessary, but it takes over the day if you let it.",
         "Newport suggests measuring how much of your time is deep versus shallow. Most people are surprised how little deep work they actually do.",
         "Batch shallow tasks together so they don't fragment your day."],
        "Estimate how many hours of deep work you did this week. Aim to add one more next week."],
      ["Schedule deep work",
        "Put focused sessions in your calendar like appointments.",
        ["If you wait for spare time, deep work won't happen. Newport describes different approaches: set daily times (rhythmic), retreat for days (bimodal) or grab time when you can (journalistic). For most people, a daily rhythm works best.",
         "Protect these blocks the way you'd protect an important meeting.",
         "Rituals help: same place, same time, same start routine."],
        "Choose a consistent daily time for deep work and put it in your calendar for the next week."],
      ["Embrace boredom",
        "If you reach for your phone every quiet moment, your brain loses the ability to concentrate.",
        ["Constantly switching to something new whenever you feel bored trains your brain to expect novelty. That makes deep focus harder.",
         "Newport suggests scheduling internet use rather than scheduling offline time, and practising sitting with boredom in lines, on walks and while waiting.",
         "Your attention span is shaped by how you use it."],
        "Next time you're waiting in a line, don't take out your phone. Just wait."],
      ["Have a shutdown ritual",
        "End work at a set time with a clear routine so your mind can properly rest.",
        ["Newport ends each workday with a shutdown ritual: review tasks, plan tomorrow, then say a phrase that marks the end of work.",
         "This helps your brain let go of unfinished tasks, which otherwise nag at you in the background. Rest improves your ability to do deep work the next day.",
         "Downtime isn't wasted time. It restores attention."],
        "Tonight, write tomorrow's top three tasks, then deliberately stop thinking about work."],
      ["Quit what doesn't pay off",
        "Drop tools and apps whose benefits don't clearly outweigh their cost to your attention.",
        ["Newport challenges the idea that any benefit justifies using a tool. Instead, ask whether its positives clearly outweigh its negatives for your most important goals.",
         "Try quitting a social platform for 30 days without announcing it. Then ask whether your life was worse without it and whether anyone noticed.",
         "Most people find they didn't miss it."],
        "Pick one app to quit for 30 days. Delete it now and see how you feel at the end."],
      ["Work in intense bursts",
        "Set a hard deadline for a task and go all in until it's done.",
        ["Newport recommends giving yourself an ambitious deadline for a task and working with full intensity to meet it. This pushes out distractions and trains focus.",
         "The key is intensity: short, fully focused sessions produce better results than long, half-distracted ones.",
         "Over time, you can extend how long you can maintain that intensity."],
        "Pick one task, set a timer for less time than you think you need, and go all out."],
      ["Be deliberate about your time",
        "Plan every minute of your working day. Not to be rigid, but to be intentional.",
        ["Newport plans his workdays in blocks. When plans change, he simply re-plans. The goal isn't strict adherence but making deliberate decisions about how time is used.",
         "Without a plan, time drifts towards whatever is easiest or loudest.",
         "Planning also exposes when you've taken on too much."],
        "Tomorrow, plan your day in 30-minute blocks and adjust as needed."]
    ]
  },
  {
    id: "obstacle", title: "The Obstacle Is the Way", short: "The Obstacle", author: "Ryan Holiday", tint: "pink",
    gist: "Built on Stoic ideas: turn problems into fuel through three disciplines of perception, action and will.",
    ideas: [
      ["Control your perception",
        "See the situation clearly, without panic or exaggeration.",
        ["The first discipline is perception: how you see a problem. Panic and emotion distort the picture, making obstacles seem bigger than they are.",
         "Holiday suggests stripping away labels: this is 'bad', 'unfair', 'a disaster'. Just look at what's actually happening.",
         "With a clear view, options often appear that fear had hidden."],
        "Describe your current biggest problem in plain, neutral language, as if reporting it to a stranger."],
      ["Keep your composure",
        "Stay steady under pressure. It's a skill you can practise.",
        ["Holiday gives examples of people staying calm in extreme situations, like astronauts trained to handle emergencies without panic.",
         "Composure comes from preparation and practice. The more you've faced difficulty, the less it rattles you.",
         "When you feel panic rising, slow down. Rushing usually makes things worse."],
        "When something goes wrong today, take three slow breaths before responding."],
      ["Act, then act again",
        "Stop waiting for the perfect moment. Start moving and adjust as you go.",
        ["The second discipline is action. Many obstacles are solved just by getting started and keeping going.",
         "Holiday emphasises persistent, deliberate action: not frantic effort, but steady pressure on the problem.",
         "Most people give up too early. Keep trying different approaches."],
        "Take one concrete action on a problem you've been stuck on today, however small."],
      ["Persist",
        "Most obstacles give way to steady, repeated effort more than to brilliance.",
        ["Holiday uses the example of Edison trying thousands of materials for a light bulb. Persistence often matters more than talent.",
         "Obstacles are rarely overcome in one go. They wear down under repeated effort.",
         "This is what a 66-day program is: persistence built into a structure."],
        "Commit to one more attempt at something you've given up on."],
      ["Find the flip side",
        "Every setback teaches something or opens a door. Ask what it makes possible.",
        ["Holiday encourages looking for the opportunity inside every obstacle. A rejection may free you for something better. A failure teaches what doesn't work.",
         "This isn't forced positivity. It's a practical search for advantage.",
         "Often, the obstacle itself points to the solution."],
        "For a recent setback, write one thing it taught you or one opportunity it created."],
      ["Prepare for the worst",
        "Think through what could go wrong ahead of time so it can't knock you over.",
        ["Stoics practised imagining what could go wrong (premeditatio malorum). Not to be pessimistic, but so they'd be ready.",
         "If you've thought about potential problems in advance, they're less shocking when they happen and you already have a plan.",
         "It also reduces anxiety, because the unknown becomes known."],
        "Before your next big task, list three things that could go wrong and how you'd handle each."],
      ["Accept what you can't change",
        "Some things just are. Make peace with them and put your energy elsewhere.",
        ["The third discipline is will: the inner strength to handle what can't be changed. Holiday calls this amor fati, loving your fate, including the hard parts.",
         "Fighting reality wastes energy. Acceptance frees that energy for what you can influence.",
         "Acceptance isn't giving up. It's the foundation for acting wisely."],
        "Name one thing you've been resisting that you can't change. Write 'I accept this' and move your focus elsewhere."],
      ["Think of others",
        "Your struggle can help someone else. Purpose makes hard things bearable.",
        ["Holiday reminds readers that obstacles become more manageable when we see them as part of something bigger than ourselves.",
         "Helping others through what you've learned gives meaning to what you've endured.",
         "It also shifts attention away from self-pity."],
        "Share something you've learned from a hard experience with someone who might benefit."]
    ]
  }
];
