// Built-in recipes for the Everyday → Recipes page. Your own pasted recipes are saved in the app.
// Shape: { id, cat: breakfast|lunch|dinner|prep|snack, title, time, serves, note?, ing: [...], steps: [...] }
window.__acRecipes = [
  // ---------- Meal prep lunches (make on Sunday, eat Monday to Friday) ----------
  { id: "prep-burrito", cat: "prep", title: "Chicken burrito bowls", time: "40 min", serves: "5 lunches",
    note: "Keeps 4 days in the fridge. Freeze the fifth portion and move it to the fridge on Wednesday night.",
    ing: ["800 g chicken thigh fillets", "2 tbsp taco seasoning", "1.5 cups long-grain rice (uncooked)", "1 can black beans, drained", "1 can corn, drained", "2 capsicums, sliced", "1 red onion, sliced", "1 lime", "Salsa, grated cheese and Greek yoghurt to serve", "Olive oil, salt"],
    steps: ["Cook the rice. Stir through the juice of half the lime and a pinch of salt.", "Toss chicken in taco seasoning and a little oil. Pan-fry 5 to 6 minutes a side until cooked through, rest, then slice.", "In the same pan, soften the capsicum and onion for 5 minutes.", "Warm the beans and corn together for 2 minutes.", "Divide rice, chicken, veg, beans and corn between 5 containers. Keep salsa, cheese and yoghurt in small separate pots so the bowl reheats well."] },
  { id: "prep-teriyaki", cat: "prep", title: "Teriyaki chicken and rice", time: "35 min", serves: "5 lunches",
    ing: ["800 g chicken breast, diced", "1.5 cups jasmine rice", "3 cups broccoli florets", "2 carrots, sliced into coins", "Sauce: 1/2 cup soy sauce, 3 tbsp honey, 2 tbsp rice vinegar, 2 cloves garlic, 1 tsp grated ginger, 1 tbsp cornflour mixed with 3 tbsp water", "Sesame seeds and spring onion"],
    steps: ["Cook the rice.", "Whisk the sauce ingredients except the cornflour slurry.", "Brown the chicken in a hot pan, about 6 minutes.", "Add the sauce, simmer 2 minutes, then stir in the slurry until glossy and thick.", "Steam or microwave the broccoli and carrot for 3 minutes so they stay crisp.", "Portion rice, chicken and veg into containers. Top with sesame seeds and spring onion."] },
  { id: "prep-mince", cat: "prep", title: "Beef and veggie mince with rice", time: "35 min", serves: "5 lunches",
    note: "Budget-friendly and reheats better than almost anything.",
    ing: ["750 g lean beef mince", "1 onion, diced", "2 cloves garlic", "1 zucchini, grated", "1 carrot, grated", "1 can diced tomatoes", "2 tbsp tomato paste", "1 tsp smoked paprika", "1 tsp cumin", "1.5 cups rice", "Handful baby spinach"],
    steps: ["Cook the rice.", "Soften onion and garlic, then brown the mince, breaking it up.", "Add zucchini, carrot, spices and tomato paste. Cook 2 minutes.", "Add tomatoes and simmer 12 minutes until thick. Stir in spinach at the end.", "Season well and portion over rice."] },
  { id: "prep-pesto", cat: "prep", title: "Pesto chicken pasta salad", time: "25 min", serves: "5 lunches",
    note: "Eat cold, so no microwave needed at uni or work.",
    ing: ["500 g short pasta", "600 g chicken breast", "1/2 jar basil pesto", "250 g cherry tomatoes, halved", "100 g baby spinach", "1 cup feta, crumbled", "1/2 cup sun-dried tomatoes, chopped", "Juice of 1 lemon"],
    steps: ["Cook pasta, rinse under cold water and drain well.", "Season and pan-fry the chicken until cooked, rest, then dice.", "Toss pasta with pesto and lemon juice.", "Fold through chicken, tomatoes, spinach, sun-dried tomatoes and feta.", "Portion into containers. Add a splash of water or extra pesto before eating if it has absorbed."] },
  { id: "prep-curry", cat: "prep", title: "Chickpea and sweet potato curry", time: "40 min", serves: "5 lunches",
    note: "Vegetarian. Tastes better on day two.",
    ing: ["2 medium sweet potatoes, cubed", "2 cans chickpeas, drained", "1 onion, diced", "3 cloves garlic", "1 tbsp grated ginger", "3 tbsp curry paste (tikka or korma)", "1 can coconut milk", "1 can diced tomatoes", "2 cups spinach", "Rice or naan to serve"],
    steps: ["Soften onion, garlic and ginger for 4 minutes.", "Stir in curry paste and cook 1 minute until fragrant.", "Add sweet potato, tomatoes and coconut milk. Simmer 20 minutes until the potato is tender.", "Add chickpeas for the last 5 minutes and wilt in the spinach.", "Portion with rice. Freezes well."] },
  { id: "prep-greek", cat: "prep", title: "Greek chicken grain bowls", time: "35 min", serves: "5 lunches",
    ing: ["800 g chicken thigh", "Marinade: 3 tbsp olive oil, juice of 1 lemon, 2 cloves garlic, 2 tsp dried oregano, salt and pepper", "1.5 cups quinoa or couscous", "2 Lebanese cucumbers, diced", "250 g cherry tomatoes", "1/2 red onion, finely sliced", "100 g feta", "Kalamata olives", "Tzatziki to serve"],
    steps: ["Marinate the chicken for at least 15 minutes (overnight is better).", "Cook quinoa or couscous and fluff with a fork.", "Grill or pan-fry the chicken 5 to 6 minutes a side, rest and slice.", "Divide grain, chicken and salad veg between containers.", "Keep tzatziki separate and add when eating."] },
  { id: "prep-meatballs", cat: "prep", title: "Turkey meatballs with couscous", time: "40 min", serves: "5 lunches",
    ing: ["750 g turkey or chicken mince", "1/2 cup breadcrumbs", "1 egg", "1/3 cup grated parmesan", "2 cloves garlic", "1 jar passata (700 g)", "1.5 cups couscous", "2 cups green beans", "Fresh basil"],
    steps: ["Mix mince, breadcrumbs, egg, parmesan, garlic, salt and pepper. Roll into about 25 balls.", "Brown in batches, then add the passata and simmer 15 minutes.", "Pour 1.5 cups boiling stock or water over the couscous, cover for 5 minutes, fluff.", "Blanch green beans for 2 minutes.", "Portion couscous, meatballs with sauce and beans. Top with basil."] },

  // ---------- Breakfast ----------
  { id: "b-oats", cat: "breakfast", title: "Protein overnight oats", time: "5 min + overnight", serves: "1",
    note: "Make 4 jars at once on Sunday night.",
    ing: ["1/2 cup rolled oats", "1/2 cup milk", "1/3 cup Greek yoghurt", "1 scoop protein powder or 1 extra tbsp yoghurt", "1 tbsp chia seeds", "1 tsp honey", "Berries or banana to top"],
    steps: ["Stir everything except the fruit in a jar.", "Refrigerate overnight.", "Top with fruit in the morning. Eat cold or microwave 1 minute."] },
  { id: "b-wraps", cat: "breakfast", title: "Freezer breakfast wraps", time: "25 min", serves: "6 wraps",
    ing: ["8 eggs", "6 large tortillas", "150 g bacon or ham, chopped", "1 cup grated cheese", "1 capsicum, diced", "2 handfuls spinach", "Salt, pepper"],
    steps: ["Cook bacon, then capsicum, then add spinach to wilt.", "Scramble the eggs softly and fold everything together with cheese.", "Divide between tortillas and roll tightly. Cool completely.", "Wrap each in baking paper and freeze.", "Microwave from frozen, still in the paper, for 1.5 to 2 minutes."] },
  { id: "b-pancakes", cat: "breakfast", title: "Banana oat pancakes", time: "15 min", serves: "2",
    ing: ["2 ripe bananas", "2 eggs", "1 cup rolled oats", "1/2 tsp baking powder", "Pinch of cinnamon", "Yoghurt and maple syrup to serve"],
    steps: ["Blend everything until smooth.", "Rest 5 minutes to thicken.", "Cook small pancakes in a lightly oiled pan, 2 minutes a side."] },
  { id: "b-parfait", cat: "breakfast", title: "Greek yoghurt parfait", time: "3 min", serves: "1",
    ing: ["1 cup Greek yoghurt", "1/3 cup granola", "Handful of berries", "1 tsp honey", "1 tbsp peanut butter (optional)"],
    steps: ["Layer yoghurt, fruit and granola in a glass or container.", "Drizzle with honey. Keep granola separate if prepping ahead so it stays crunchy."] },

  // ---------- Lunch ----------
  { id: "l-caesar", cat: "lunch", title: "Chicken caesar wrap", time: "10 min", serves: "1",
    ing: ["1 large tortilla", "100 g cooked chicken, sliced", "Cos lettuce, shredded", "1 tbsp caesar dressing", "1 tbsp parmesan", "Crispy bacon (optional)"],
    steps: ["Toss lettuce with dressing and parmesan.", "Pile onto the wrap with chicken and bacon.", "Roll tightly and cut in half."] },
  { id: "l-tuna", cat: "lunch", title: "Tuna and white bean salad", time: "10 min", serves: "2",
    ing: ["1 can tuna in oil, drained", "1 can cannellini beans, drained", "1/2 red onion, finely diced", "Cherry tomatoes", "Handful rocket", "Juice of 1/2 lemon", "1 tbsp olive oil", "Parsley"],
    steps: ["Combine beans, onion and tomatoes.", "Flake in the tuna.", "Dress with lemon, oil, salt and pepper. Toss through rocket and parsley."] },
  { id: "l-potato", cat: "lunch", title: "Loaded sweet potato", time: "15 min", serves: "1",
    ing: ["1 sweet potato", "1/2 can black beans", "Grated cheese", "Greek yoghurt", "Spring onion", "Hot sauce"],
    steps: ["Prick the potato and microwave 8 to 10 minutes until soft.", "Split open and fill with warmed beans and cheese.", "Top with yoghurt, spring onion and hot sauce."] },

  // ---------- Dinner ----------
  { id: "d-lemon", cat: "dinner", title: "One-pan lemon garlic chicken and veg", time: "45 min", serves: "4",
    ing: ["6 chicken thigh fillets", "500 g baby potatoes, halved", "2 zucchini, chunked", "1 red onion, wedged", "4 cloves garlic", "1 lemon", "2 tsp dried oregano", "3 tbsp olive oil"],
    steps: ["Heat oven to 210°C.", "Toss potatoes with oil and salt, roast 15 minutes.", "Add chicken, zucchini, onion, garlic, oregano and lemon slices. Roast 25 minutes more.", "Squeeze over the roasted lemon to serve."] },
  { id: "d-stirfry", cat: "dinner", title: "Beef and broccoli stir-fry", time: "20 min", serves: "3",
    ing: ["400 g beef strips", "1 head broccoli", "1 capsicum", "2 cloves garlic", "Sauce: 3 tbsp soy, 1 tbsp oyster sauce, 1 tsp sesame oil, 1 tsp cornflour, 3 tbsp water", "Rice or noodles"],
    steps: ["Mix the sauce.", "Sear beef in a very hot pan in two batches, then remove.", "Stir-fry veg and garlic for 3 minutes.", "Return beef, pour in sauce and toss until glossy. Serve over rice."] },
  { id: "d-salmon", cat: "dinner", title: "Honey soy salmon with rice and greens", time: "20 min", serves: "2",
    ing: ["2 salmon fillets", "2 tbsp soy sauce", "1 tbsp honey", "1 tsp grated ginger", "1 cup rice", "Bok choy or broccolini", "Sesame seeds"],
    steps: ["Cook the rice.", "Mix soy, honey and ginger.", "Pan-fry salmon skin-side down 4 minutes, flip, pour over the sauce and cook 2 more minutes.", "Steam the greens and serve with rice, spooning over the pan sauce."] },
  { id: "d-bolognese", cat: "dinner", title: "Big-batch spaghetti bolognese", time: "1 hr", serves: "6",
    note: "Freeze half the sauce for a no-effort dinner later.",
    ing: ["1 kg beef mince", "1 onion, 1 carrot, 1 celery stick, finely diced", "3 cloves garlic", "2 cans diced tomatoes", "2 tbsp tomato paste", "1 cup beef stock", "1 tsp dried Italian herbs", "Spaghetti and parmesan"],
    steps: ["Soften onion, carrot and celery for 8 minutes.", "Add garlic, then brown the mince.", "Stir in paste, tomatoes, stock and herbs.", "Simmer uncovered 40 minutes, stirring now and then.", "Serve over spaghetti with parmesan."] },

  // ---------- Snacks ----------
  { id: "s-balls", cat: "snack", title: "Peanut butter protein balls", time: "10 min", serves: "14 balls",
    ing: ["1 cup rolled oats", "1/2 cup peanut butter", "1/3 cup honey", "1 scoop protein powder", "1/3 cup dark choc chips", "2 tbsp chia seeds"],
    steps: ["Mix everything in a bowl.", "Chill 20 minutes, then roll into balls.", "Keep in the fridge for up to a week."] },
  { id: "s-hummus", cat: "snack", title: "Quick hummus snack box", time: "5 min", serves: "1",
    ing: ["1/3 cup hummus", "Carrot and cucumber sticks", "Cherry tomatoes", "A few crackers", "Boiled egg (optional)"],
    steps: ["Pack everything into a divided container.", "Keep cold until eating."] }
];
